name: My First GitHub-Actions CICD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile with Maven
      run: mvn clean package
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-app
        path: target/*.jar

    - name: Run the app
      run: |
        nohup java -jar target/*.jar &
        sleep 10

    - name: Test application is running
      run: curl http://localhost:8080
